# Copyright 2019-2021 The Kubeflow Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This docker file starts server.py (located at src/apiserver/visualization)
# which accepts a post request that resolves to html that depicts a specified
# visualization. More details about this process can be found in the server.py
# and exporter.py files in the directory specified above.

# This image should be in sync with image in backend/src/apiserver/visualization/update_requirements.sh.
FROM tensorflow/tensorflow:2.10.1

RUN apt-get update \
  && apt-get install -y wget curl tar openssl

RUN curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-461.0.0-linux-x86_64.tar.gz> /tmp/google-cloud-sdk.tar.gz

RUN mkdir -p /usr/local/gcloud
RUN tar -C /usr/local/gcloud -xf /tmp/google-cloud-sdk.tar.gz
RUN /usr/local/gcloud/google-cloud-sdk/install.sh
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

WORKDIR /src

COPY backend/src/apiserver/visualization/requirements.txt /src

RUN python3 -m pip install -r requirements.txt --no-cache-dir
 
COPY backend/src/apiserver/visualization /src

RUN rm -rf /usr/local/lib/python3.8/dist-packages/tornado/test
RUN rm -rf /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/urllib3/dummyserver/certs/cacert.key
RUN rm -f  /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/urllib3/dummyserver/certs/server.key
RUN rm -rf /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/google-auth-library-python/tests/data/privatekey.pem
RUN rm -rf /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/google-auth-library-python/tests
RUN rm -rf /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/google-auth-library-python/tests/data/pem_from_pkcs12.pem
RUN rm -rf /usr/local/gcloud/google-cloud-sdk/platform/gsutil/third_party/google-auth-library-python/tests/data/es256_privatekey.pem
 

ENTRYPOINT [ "python3", "server.py" ]


# https://github.com/kubeflow/pipelines/blob/1.8.2/backend/Dockerfile
# docker build -f backend/Dockerfile.visualization .  -t  kubef/kp-visualization-server:1.8.2